version: '2'
volumes:
  postgres-data: {}
  shuttle-data: {}
services:
  logstash:
    image: registry.shuttle-cloud.com:5000/slaheddinne.ahmed/logstash-shuttle
    environment:
      EL_HOST: es
      EL_PORT: 9243
      EL_INDEX: staging_prod
      EL_USER: logstash 
      EL_PASSWORD: logstash 
      EL_SSL: 'true' 
      EL_SSL_VERIF_CERT: 'false'
      LOG_VERSION: v01
      LOG_BASE_DIR: /data/shuttle/home/logs 
      AUDIT_FILES: audit/ShuttleAudit.csv 
      USERS_FILES: users/users 
      OUTPUT_ONLY: 'false' 
    networks:
      - default
      - elasticsearch_default    
    volumes:
    - shuttle-data:/data
    
    tty: true
    command:
    - --run
  shuttle:
    image: registry.shuttle-cloud.com:5000/shuttle:4.7.0
    environment:
      CATALINA_OPTS: -Xms512m -Xmx8192m -XX:MaxPermSize=256m -Dfile.encoding=UTF-8 -Djava.awt.headless=true
      DB_HOST: postgres95
      DB_PORT: '5432'
      DB_SHUTTLE_PASSWORD: password
      DB_SHUTTLE_REPO: SHUT_REPO
      DB_SHUTTLE_USER: shuttle
      DB_SYSTEM_PASSWORD: mysecretpassword
      DB_SYSTEM_USER: postgres
      EXTERNAL_URL_PORT: '443'
      EXTERNAL_URL_PROTOCOL: https
      EXTERNAL_URL_SERVER: demo.shuttle-cloud.com
      LICENSEKEY: KEY= Change it 
      WEBAPP_NAME: LOGS
    stdin_open: true
    volumes:
    - shuttle-data:/data
    tty: true
    command:
    - --run
  postgres95:
    image: postgres:9.5.9
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    stdin_open: true
    volumes:
    - postgres-data:/var/lib/postgresql/data
    tty: true
networks:
  elasticsearch_default:
    external:
      name: elasticsearch_default 